FORMAT: 1A
HOST: http://director.myaccessone.com/

# AccessOne Director

The AccessOne Director is a full service API for performing internal & external tasks for both Blaze and Pharos platforms.

# Group Accounts

## Account Collection [/a-accounts/{system%2Did}/{client%2Did}?{s}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + s (string, optional) - Search Criteria

### Create Account [POST]
Create an AccessOne account.

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 201 (application/json)

    + Headers
    
            Location: /a-accounts/bz/1/2
            
    + Body
    
            {
                "foo": "value"
            }

### View Accounts [GET]
Get all accounts for a given client.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]
        
## Account [/a-accounts/{system%2Did}/{client%2Did}/{account%2Did}]
View, update or delete an AccessOne account.

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number

### View Account [GET]

+ Response 200 (application/json)

        {
            "foo": "value"
        }

### Update Account [PATCH]

+ Request (application/json)

        {
            "foo": "value"
        }
        
+ Response 200 (application/json)

    + Headers
    
            Location: /a-accounts/bz/1/2
            
    + Body
    
            {
                "foo": "value"
            }

### Delete Account [DELETE]

+ Response 204 (application/json)

# Group Clients

## Clients Collection [/clients/{system%2Did}{?s}]

+ Parameters
    + system%2Did (string) - System Identifier. User bz for Blaze. Use ph for Pharos.
    + s (string, optional) - Search Criteria

### Create Client [POST]
Create a client on Blaze or Pharos.

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 201 (application/json)

    + Headers
    
            Location: /clients/bz/1
    
    + Body
        
            {
                "foo": "value"
            }

### View Clients [GET]
View all clients for Blaze or Pharos.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

## Client [/clients/{system%2Did}/{client%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier

### View Client [GET]
View details of a client.

+ Response 200 (application/json)

        {
            "foo": "value"
        }

### Update Client [PATCH]
Update details of a client.

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 200 (application/json)

    + Headers
            
            Location: /clients/bz/1
            
    + Body

            {
                "foo": "value"
            }

# Group Events

## Events Collection [/events/{system%2Did}/{client%2Did}/{account%2Did}{?s}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number
    + s (string, optional) - Search Criteria

### Create Account Events [POST]
Create events for an account.

+ Request (application/json)

        [
            {
                "foo": "value"
            }
        ]
        
+ Response 204

### Get Account Events [GET]
View all events for an account.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

## Event [/events/{system%2Did}/{client%2Did}/{account%2Did}/{event%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number
    + event%2Did (string) - Event Identifier

### View Event [GET]
View details of an event.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

# Group Persons

## Persons Collection [/persons/{system%2Did}/{client%2Did}{?s}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + s (string, optional) - Search Criteria

### Create Person [POST]
Add a person to AccessOne.

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 201 (application/json)

    + Headers
            
            Location: /persons/bz/1/1234
            
    + Body
    
            {
                "foo": "value"
            }

### View Persons [GET]
View all persons.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

## Person [/persons/{system%2Did}/{client%2Did}/{account%2Did}]
Person contains demographic information about an account holder.

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number

### View Person [GET]

+ Response 200 (application/json)

        {
            "foo": "value"
        }

### Update Person [PATCH]

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 204 (application/json)

    + Headers
            
            Location: /persons/bz/1/1234

# Group Notifications

## Notification [/notifications/{system%2Did}/{client%2Did}/{account%2Did}/{notificationtype%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number
    + notificationtype%2Did (string) - Notification Type Identifier

### Send Notification [POST]

+ Request (application/json)

        {
            "foo": "value"
        }
        
+ Response 204

### View Notification [GET]

+ Response 200 (application/json)

        {
            "foo": "value"
        }

# Group Patients

## Patient Collection [/patients/{system%2Did}/{client%2Did}/{account%2Did}]
View all patient accounts for a given AccessOne account.

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number

### View Patients [GET]

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

## Patient [/patients/{system%2Did}/{client%2Did}/{account%2Did}/{patient%2Did}]
Patient contains demographic information about hospital/physician accounts for a Guarantor. 

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number
    + patient%2Did (string) - Patient Identifier (assigned by AccessOne, this is not the hospital account number)

### View Patient [GET]

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

### Update Patient [PATCH]

+ Request (application/json)

        {
            "foo": "value"
        }
        
+ Response 201 (application/json)

    + Headers
    
            Location: /patients/bz/1/7890/1111
            
    + Body
    
            {
                "foo": "value"
            }

### Create Patient [POST]

+ Request (application/json)

        {
            "foo": "value"
        }
        
+ Response 201 (application/json)

    + Headers
    
            Location: /patients/bz/1/7890/1111
            
    + Body
    
            {
                "foo": "value"
            }

### Delete Patient [DELETE]

+ Response 204 (application/json)

# Group Payments

## Payments Collection [/payments/{system%2Did}/{client%2Did}/{account%2Did}]
View all payment history for a given AccessOne account.

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number

### View Payments [GET]

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

# Group Providers

## Providers Collection [/providers/{system%2Did}/{client%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. User bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier

### Create Provider [POST]
Create a provider on a Blaze or Pharos client.

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 201 (application/json)

    + Headers
    
            Location: /providers/bz/1/2
    
    + Body
    
            {
                "foo": "value"
            }

### View Providers [GET]
View all providers for a Blaze or Pharos client.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

## Provider [/providers/{system%2Did}/{client%2Did}/{provider%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + provider%2Did (string) - Provider Identifier

### View Provider [GET]
View details of a provider.

+ Response 200 (application/json)

        {
            "foo": "value"
        }

### Update Provider [PATCH]
Update details of a provider.

+ Request (application/json)

        {
            "foo": "value"
        }

+ Response 204

# Group Provider Accounts

## Provider Account Collection [/p-accounts/{system%2Did}/{client%2Did}/{account%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + account%2Did (string) - AccessOne Account Number

### Get Provider Accounts [GET]
View all provider accounts for an AccessOne account.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

### Create Provider Account [POST]
Create a provider account for an AccessOne account.

+ Request (application/json)

        {
            "foo": "value"
        }
            
+ Response 201 (application/json)

    + Headers
    
            Location: /a-accounts/bz/1/2/3
            
    + Body
    
            {
                "foo": "value"
            }

# Group Transactions

## Transaction Collection [/transactions/{system%2Did}/{client%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier

### Create Transactions [POST]
Submit a batch of transactions.

+ Request (application/json)

        [
            {
                "foo": "value"
            }
        ]

+ Response 201 (application/json)

    + Headers
        
            Location: /transactions/bz/2/3

## Batch Collection [/transactions/{system%2Did}/{client%2Did}/{batch%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + batch%2Did (string ) - Batch Identifier

### View Batch [GET]
View a batch of transactions.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

## Transaction [/transactions/{system%2Did}/{client%2Did}/{transaction%2Did}]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + client%2Did (string) - Client Identifier
    + transaction%2Did (string ) - Transaction Identifier

### View Transaction [GET]
View a single transaction.

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]
        
### Update Transaction [PATCH]
Update a single transaction.

+ Response 204 (application/json)

### Delete Transaction [DELETE]
Delete a single transaction.

+ Response 204 (applicatin/json)

# Group Users

## User [/users/{system%2Did}/{user%2Did}]
Create, view, update or delete an online user account.

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + user%2Did (string) - User identifier

### Create User [POST]

+ Response 204 (application/json)

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + user%2Did (string) - User identifier

### View User [GET]

+ Response 200 (application/json)

        [
            {
                "foo": "value"
            }
        ]

### Update User [PATCH]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + user%2Did (string) - User identifier

+ Response 204 (application/json)

### Delete User [DELETE]

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + user%2Did (string) - User identifier

+ Response 204 (application/json)

## Activate User [/users/activate/{system%2Did}/{user%2Did}]
Activate a user's online account.

+ Parameters
    + system%2Did (string) - System Identifier. Use bz for Blaze. Use ph for Pharos.
    + user%2Did (string) - User identifier